In [2]:
import pandas as pd
df_lung = pd.read_csv('data/lung_cancer.csv')
df_lung

      age  gender  ...  healthcare_access  lung_cancer_risk
0      60       1  ...                  3                 1
1      53       0  ...                  3                 0
2      62       1  ...                  1                 1
3      73       1  ...                  4                 0
4      52       1  ...                  2                 0
...   ...     ...  ...                ...               ...
4995   54       1  ...                  4                 0
4996   63       0  ...                  2                 0
4997   90       0  ...                  1                 0
4998   64       0  ...                  2                 1
4999   44       1  ...                  3                 0

[5000 rows x 30 columns]

In [3]:
df_lung.describe()

               age       gender  ...  healthcare_access  lung_cancer_risk
count  5000.000000  5000.000000  ...        5000.000000       5000.000000
mean     54.566400     0.488200  ...           2.536800          0.248800
std      11.932731     0.499911  ...           0.984093          0.432361
min      18.000000     0.000000  ...           1.000000          0.000000
25%      47.000000     0.000000  ...           2.000000          0.000000
50%      55.000000     0.000000  ...           3.000000          0.000000
75%      62.000000     1.000000  ...           3.000000          0.000000
max      90.000000     1.000000  ...           5.000000          1.000000

[8 rows x 30 columns]